config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users

  resources :beers

  resources :breweries

	resources :ratings, :only => [:index, :new, :create, :destroy]

	root 'breweries#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'ngbrewerylist', to:'breweries#nglist'

  resources :places, :only => [:index, :show]
  
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
	include RatingAverage

	has_many :beers, :dependent => :destroy
	has_many :ratings, :through => :beers

  validates :name, presence: true
  validates :year, numericality: { greater_than_or_equal_to: 1042,
                                    only_integer: true }
  validate :year, :year_cannot_be_in_the_future

  def print_report
    puts name
    puts "Established year: #{year}"
    puts "Number of beers #{beers.count}"
    puts "Number of ratings #{ratings.count}"
  end


  def restart
    self.year = 2014
    puts "changed year to #{year}"
  end


  def year_cannot_be_in_the_future
    errors.add(:year, 'cannot be in the future') unless year <= Time.now.year
  end

  def to_s
    "#{name} #{year}"
  end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :nglist]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all

    order = params[:order] || 'name'

    case order
      when 'name' then @breweries.sort_by!{ |b| b.name }
      when 'year' then @breweries.sort_by!{ |b| b.year }
    end

  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  def nglist
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brewery }
      else
        format.html { render action: 'new' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    if current_user.admin
      @brewery.destroy
      respond_to do |format|
        format.html { redirect_to breweries_url }
        format.json { head :no_content }
      end
    else
      redirect_to :back
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year)
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Listing breweries</h1>

<p> Number of breweries: <%= @breweries.count %> </p> 

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= link_to 'Name', breweries_path(order: "name") %></th>
      <th><%= link_to 'Year', breweries_path(order: "year")%></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td><%= link_to 'Edit', edit_brewery_path(brewery) %></td>
        <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'list of beers', beers_path %>
<br>
<%= link_to('New Brewery', new_brewery_path) if current_user %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/nglist.html.erb
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.min.js"></script>
<script>
    function BreweriesController($scope, $http) {
        $http.get('breweries.json').success( function(data, status, headers, config) {
            $scope.breweries = data;
            console.log(data);
        });

        $scope.order = 'name';

        $scope.click = function (order){
            $scope.order = order;
            console.log(order);
        }

        $scope.searchText = '';
    }
</script>

<h2>Breweries</h2>

<div ng-app ng-controller="BreweriesController">
  search:  <input ng-model="searchText">

  <table class="table table-hover">
    <thead>
    <th> <a ng-click="click('name')">name</a> </th>
    <th> <a ng-click="click('year')">year</a> </th>
    <th> <a ng-click="click('brewery.beers.count')">beers</a> </th>
    </thead>
    <tr ng-repeat="brewery in breweries| orderBy:order | filter:searchText">
      <td>{{brewery.name}}</td>
      <td>{{brewery.year}}</td>
      <td>{{brewery.beers.count}}</td>
    </tr>
  </table>

</div>

app/views/breweries/panimot.html.erb
<%= @breweries.count %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @brewery.name %>
</h2>

<p>
  <i>Established year: <%= @brewery.year %></i>
</p>

<% if !@brewery.ratings.empty? %>
    <%= "Has #{pluralize(@brewery.ratings.count, "rating")}, average #{@brewery.average_rating}" %>
<% end %>


<p>
	<strong>Beers:</strong>
	<%= @brewery.beers.count %>
</p>

<p>
 <% @brewery.beers.each do |beer| %>
   <%= link_to beer.name, beer %>
 <% end %>
</p>

<%= link_to 'Edit', edit_brewery_path(@brewery) %> 